on:
  push:
    branches:
    - main

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Git repo
        run: |
          pwd
          ls
      - name: OC or kubectl
        run: |
          oc version
      
    
