on:
  push:
    branches:
    - main

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Git repo
        run: |
          pwd
          ls
      - name: oc login
        run: oc login --token=${{ secrets.OCP_TOKEN }} --server=https://api.devops24.cloud2.se:6443
      - name: oc project
        run: oc project test-miljo2
      - name: oc get
        run: oc get pods
      
    
